// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5FWoprFGBT9tIeGJD8mKJPkYA1t2y5f8',
    appId: '1:952573746147:web:d577bd4de775f53d4a9ed6',
    messagingSenderId: '952573746147',
    projectId: 'amit58-e49e4',
    authDomain: 'amit58-e49e4.firebaseapp.com',
    storageBucket: 'amit58-e49e4.appspot.com',
    measurementId: 'G-5EHHEW6NF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTNpLS5ZLTlq6V8Tl_rHWXKZ8UNX7roMo',
    appId: '1:952573746147:android:d18943a0933ccdaa4a9ed6',
    messagingSenderId: '952573746147',
    projectId: 'amit58-e49e4',
    storageBucket: 'amit58-e49e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUT3sOzQxIFZ_j9O_8D8qaMFzzQ1Mmhe0',
    appId: '1:952573746147:ios:7393924b0a93ba7a4a9ed6',
    messagingSenderId: '952573746147',
    projectId: 'amit58-e49e4',
    storageBucket: 'amit58-e49e4.appspot.com',
    iosBundleId: 'com.example.socialmedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUT3sOzQxIFZ_j9O_8D8qaMFzzQ1Mmhe0',
    appId: '1:952573746147:ios:5aaa138ba0e2b63e4a9ed6',
    messagingSenderId: '952573746147',
    projectId: 'amit58-e49e4',
    storageBucket: 'amit58-e49e4.appspot.com',
    iosBundleId: 'com.example.socialmedia.RunnerTests',
  );
}
